"""Regenerate demo/data.js from the source curriculum dataset in the UGRP_2026 repo.

Run with the UGRP_2026 repo checked out as a sibling directory:
  ../UGRP_2026/UG_2026_curriculum_courses.jsonl
  ../UGRP_2026/UG_2026_prerequisites_merged.jsonl
  ../UGRP_2026/UG_2026_axisD_hasSynergyWith.jsonl

Usage: python3 scripts/build_demo_data.py [path-to-UGRP_2026]
"""
import collections
import json
import os
import re
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), "..", "..", "UGRP_2026")
OUT = os.path.join(os.path.dirname(__file__), "..", "demo", "data.js")

DEPT_NAMES = {
    "AMSE": "신소재공학과", "CHEB": "화학공학과", "CHEM": "화학과",
    "CITE": "IT융합공학과", "CMEF": "경제경영 교양(CMEF)", "CSED": "컴퓨터공학과",
    "DISU": "반도체특성화학부(DISU)", "EECE": "전자전기공학과", "ENTP": "기업가정신학부(ENTP)",
    "IMEN": "산업경영공학과", "LIFE": "생명과학과", "MATH": "수학과",
    "MECH": "기계공학과", "PHYS": "물리학과", "SEMI": "반도체공학과",
}


def dept_of(code):
    m = re.match(r"^[A-Za-z]+", code)
    return m.group(0) if m else "?"


def trim(s, n):
    if not s:
        return ""
    s = re.sub(r"\s+", " ", s).strip()
    return s if len(s) <= n else s[:n].rstrip() + "…"


def main():
    courses = []
    with open(os.path.join(SRC, "UG_2026_curriculum_courses.jsonl"), encoding="utf-8") as f:
        for line in f:
            d = json.loads(line)
            code = d["course_code"]
            text = d.get("content") or ""
            if len(text) < 10:
                text = d.get("course_objectives") or text
            courses.append({
                "code": code,
                "dept": dept_of(code),
                "kr": d.get("course_name_kr", ""),
                "en": d.get("course_name_en", ""),
                "desc": trim(text, 160),
                "corpus": d.get("course_name_kr", "") + " " + (d.get("content") or ""),
            })

    prereq_map = {}
    with open(os.path.join(SRC, "UG_2026_prerequisites_merged.jsonl"), encoding="utf-8") as f:
        for line in f:
            d = json.loads(line)
            prereq_map[d["course_code"]] = d.get("prerequisites") or []

    reverse_map = collections.defaultdict(list)
    for code, prereqs in prereq_map.items():
        for p in prereqs:
            reverse_map[p].append(code)

    synergy = []
    with open(os.path.join(SRC, "UG_2026_axisD_hasSynergyWith.jsonl"), encoding="utf-8") as f:
        for line in f:
            d = json.loads(line)
            synergy.append({
                "a": d["anchor_course"], "b": d["positive_course"],
                "conf": d.get("confidence", 0),
            })

    print("courses:", len(courses))
    print("prereq entries:", len(prereq_map))
    print("synergy entries:", len(synergy))

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/build_demo_data.py from the POSTECH UGRP curriculum dataset\n")
        f.write("// (sternjeong/UGRP_2026 repo). Real data, not mocked. Do not hand-edit.\n")
        f.write("window.UGRP_DATA = ")
        json.dump({
            "deptNames": DEPT_NAMES,
            "courses": courses,
            "prereqMap": prereq_map,
            "reverseMap": dict(reverse_map),
            "synergy": synergy,
        }, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")

    print("output size (KB):", round(os.path.getsize(OUT) / 1024, 1))


if __name__ == "__main__":
    main()
